/**
 * Apply translations to the "common" and "theme" sections of each language file.
 * Run: node scripts/translate-common.mjs
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const i18nDir = join(__dirname, '..', 'src', 'lib', 'i18n');

function applyTranslations(lang, common, theme) {
    const filePath = join(i18nDir, `${lang}.json`);
    const data = JSON.parse(readFileSync(filePath, 'utf-8'));
    data.common = { ...data.common, ...common };
    data.theme = { ...data.theme, ...theme };
    writeFileSync(filePath, JSON.stringify(data, null, 4) + '\n', 'utf-8');
    console.log(`Updated ${lang}.json common+theme`);
}

// German
applyTranslations('de', {
    description: "Interaktive Lernerfahrung", facilitator: "Moderator", attendee: "Teilnehmer", login: "Anmelden", logout: "Abmelden", save: "Speichern", cancel: "Abbrechen", delete: "Löschen", create: "Erstellen", import: "Importieren", export: "Exportieren", copy: "Kopieren", loading: "Laden...", send: "Senden", actions: "Aktionen", author: "Autor", date: "Datum", status: "Status", error: "Fehler", success: "Erfolg", failed: "fehlgeschlagen", photo: "Foto", toggle_colorblind: "Farbenblind-Modus", tts_read: "Vorlesen", tts_stop: "Stoppen", google_login: "Mit Google anmelden", github_repo: "GitHub-Repository", documentation: "Dokumentation", change_language: "Sprache ändern", conversations: "Unterhaltungen", total: "gesamt", refresh: "Aktualisieren", question: "Frage", answer: "Antwort", select_item: "Element auswählen", no_data: "Keine Daten", toggle_theme: "Design umschalten", or: "ODER", optional: "Optional", required: "Erforderlich", ai_assistant: "KI-Assistent", close: "Schließen", visibility: "Sichtbarkeit", public: "Öffentlich", private: "Privat", skip_to_main: "Zum Hauptinhalt", download: "Herunterladen", open_new_tab: "In neuem Tab öffnen", confirm_delete: "Möchten Sie dieses Element wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden."
}, { menu_label: "Design", mode_label: "Modus", preset_label: "Voreinstellung", modes: { system: "System", light: "Hell", dark: "Dunkel" }, presets: { default: "Standard", mint: "Minze", ocean: "Ozean", sunset: "Sonnenuntergang", forest: "Wald", berry: "Beere", slate: "Schiefer" } });

// Spanish
applyTranslations('es', {
    description: "Experiencia de aprendizaje interactiva", facilitator: "Facilitador", attendee: "Asistente", login: "Iniciar sesión", logout: "Cerrar sesión", save: "Guardar", cancel: "Cancelar", delete: "Eliminar", create: "Crear", import: "Importar", export: "Exportar", copy: "Copiar", loading: "Cargando...", send: "Enviar", actions: "Acciones", author: "Autor", date: "Fecha", status: "Estado", error: "Error", success: "Éxito", failed: "fallido", photo: "Foto", toggle_colorblind: "Modo daltónico", tts_read: "Leer este paso", tts_stop: "Dejar de leer", google_login: "Iniciar sesión con Google", github_repo: "Repositorio GitHub", documentation: "Documentación", change_language: "Cambiar idioma", conversations: "Conversaciones", total: "total", refresh: "Actualizar", question: "Pregunta", answer: "Respuesta", select_item: "Seleccionar elemento para ver detalles", no_data: "Sin datos disponibles", toggle_theme: "Cambiar tema", or: "O", optional: "Opcional", required: "Requerido", ai_assistant: "Asistente IA", close: "Cerrar", visibility: "Visibilidad", public: "Público", private: "Privado", skip_to_main: "Ir al contenido principal", download: "Descargar", open_new_tab: "Abrir en nueva pestaña", confirm_delete: "¿Está seguro de que desea eliminar este elemento? Esta acción no se puede deshacer."
}, { menu_label: "Tema", mode_label: "Modo", preset_label: "Preajuste", modes: { system: "Sistema", light: "Claro", dark: "Oscuro" }, presets: { default: "Predeterminado", mint: "Menta", ocean: "Océano", sunset: "Atardecer", forest: "Bosque", berry: "Baya", slate: "Pizarra" } });

// French
applyTranslations('fr', {
    description: "Expérience d'apprentissage interactive", facilitator: "Animateur", attendee: "Participant", login: "Connexion", logout: "Déconnexion", save: "Enregistrer", cancel: "Annuler", delete: "Supprimer", create: "Créer", import: "Importer", export: "Exporter", copy: "Copier", loading: "Chargement...", send: "Envoyer", actions: "Actions", author: "Auteur", date: "Date", status: "Statut", error: "Erreur", success: "Succès", failed: "échoué", photo: "Photo", toggle_colorblind: "Mode daltonien", tts_read: "Lire cette étape", tts_stop: "Arrêter la lecture", google_login: "Se connecter avec Google", github_repo: "Dépôt GitHub", documentation: "Documentation", change_language: "Changer de langue", conversations: "Conversations", total: "total", refresh: "Actualiser", question: "Question", answer: "Réponse", select_item: "Sélectionner un élément", no_data: "Aucune donnée disponible", toggle_theme: "Changer le thème", or: "OU", optional: "Facultatif", required: "Requis", ai_assistant: "Assistant IA", close: "Fermer", visibility: "Visibilité", public: "Public", private: "Privé", skip_to_main: "Aller au contenu principal", download: "Télécharger", open_new_tab: "Ouvrir dans un nouvel onglet", confirm_delete: "Voulez-vous vraiment supprimer cet élément ? Cette action est irréversible."
}, { menu_label: "Thème", mode_label: "Mode", preset_label: "Préréglage", modes: { system: "Système", light: "Clair", dark: "Sombre" }, presets: { default: "Par défaut", mint: "Menthe", ocean: "Océan", sunset: "Coucher de soleil", forest: "Forêt", berry: "Baie", slate: "Ardoise" } });

// Indonesian
applyTranslations('id', {
    description: "Pengalaman belajar interaktif", facilitator: "Fasilitator", attendee: "Peserta", login: "Masuk", logout: "Keluar", save: "Simpan", cancel: "Batal", delete: "Hapus", create: "Buat", import: "Impor", export: "Ekspor", copy: "Salin", loading: "Memuat...", send: "Kirim", actions: "Tindakan", author: "Penulis", date: "Tanggal", status: "Status", error: "Kesalahan", success: "Berhasil", failed: "gagal", photo: "Foto", toggle_colorblind: "Mode buta warna", tts_read: "Baca langkah ini", tts_stop: "Berhenti membaca", google_login: "Masuk dengan Google", github_repo: "Repositori GitHub", documentation: "Dokumentasi", change_language: "Ubah bahasa", conversations: "Percakapan", total: "total", refresh: "Segarkan", question: "Pertanyaan", answer: "Jawaban", select_item: "Pilih item untuk melihat detail", no_data: "Tidak ada data", toggle_theme: "Ubah tema", or: "ATAU", optional: "Opsional", required: "Wajib", ai_assistant: "Asisten AI", close: "Tutup", visibility: "Visibilitas", public: "Publik", private: "Privat", skip_to_main: "Langsung ke konten utama", download: "Unduh", open_new_tab: "Buka di tab baru", confirm_delete: "Anda yakin ingin menghapus item ini? Tindakan ini tidak dapat dibatalkan."
}, { menu_label: "Tema", mode_label: "Mode", preset_label: "Prasetel", modes: { system: "Sistem", light: "Terang", dark: "Gelap" }, presets: { default: "Default", mint: "Mint", ocean: "Lautan", sunset: "Matahari Terbenam", forest: "Hutan", berry: "Beri", slate: "Batu Tulis" } });

// Italian
applyTranslations('it', {
    description: "Esperienza di apprendimento interattiva", facilitator: "Facilitatore", attendee: "Partecipante", login: "Accedi", logout: "Esci", save: "Salva", cancel: "Annulla", delete: "Elimina", create: "Crea", import: "Importa", export: "Esporta", copy: "Copia", loading: "Caricamento...", send: "Invia", actions: "Azioni", author: "Autore", date: "Data", status: "Stato", error: "Errore", success: "Successo", failed: "fallito", photo: "Foto", toggle_colorblind: "Modalità daltonico", tts_read: "Leggi questo passaggio", tts_stop: "Interrompi lettura", google_login: "Accedi con Google", github_repo: "Repository GitHub", documentation: "Documentazione", change_language: "Cambia lingua", conversations: "Conversazioni", total: "totale", refresh: "Aggiorna", question: "Domanda", answer: "Risposta", select_item: "Seleziona un elemento per i dettagli", no_data: "Nessun dato disponibile", toggle_theme: "Cambia tema", or: "O", optional: "Facoltativo", required: "Obbligatorio", ai_assistant: "Assistente IA", close: "Chiudi", visibility: "Visibilità", public: "Pubblico", private: "Privato", skip_to_main: "Vai al contenuto principale", download: "Scarica", open_new_tab: "Apri in nuova scheda", confirm_delete: "Sei sicuro di voler eliminare questo elemento? Questa azione non può essere annullata."
}, { menu_label: "Tema", mode_label: "Modalità", preset_label: "Preimpostazione", modes: { system: "Sistema", light: "Chiaro", dark: "Scuro" }, presets: { default: "Predefinito", mint: "Menta", ocean: "Oceano", sunset: "Tramonto", forest: "Foresta", berry: "Bacca", slate: "Ardesia" } });

// Polish
applyTranslations('pl', {
    description: "Interaktywne doświadczenie edukacyjne", facilitator: "Prowadzący", attendee: "Uczestnik", login: "Zaloguj", logout: "Wyloguj", save: "Zapisz", cancel: "Anuluj", delete: "Usuń", create: "Utwórz", import: "Importuj", export: "Eksportuj", copy: "Kopiuj", loading: "Ładowanie...", send: "Wyślij", actions: "Akcje", author: "Autor", date: "Data", status: "Status", error: "Błąd", success: "Sukces", failed: "niepowodzenie", photo: "Zdjęcie", toggle_colorblind: "Tryb daltonizmu", tts_read: "Przeczytaj ten krok", tts_stop: "Zatrzymaj czytanie", google_login: "Zaloguj przez Google", github_repo: "Repozytorium GitHub", documentation: "Dokumentacja", change_language: "Zmień język", conversations: "Rozmowy", total: "łącznie", refresh: "Odśwież", question: "Pytanie", answer: "Odpowiedź", select_item: "Wybierz element, aby zobaczyć szczegóły", no_data: "Brak danych", toggle_theme: "Zmień motyw", or: "LUB", optional: "Opcjonalne", required: "Wymagane", ai_assistant: "Asystent AI", close: "Zamknij", visibility: "Widoczność", public: "Publiczny", private: "Prywatny", skip_to_main: "Przejdź do treści", download: "Pobierz", open_new_tab: "Otwórz w nowej karcie", confirm_delete: "Czy na pewno chcesz usunąć ten element? Tej akcji nie można cofnąć."
}, { menu_label: "Motyw", mode_label: "Tryb", preset_label: "Preset", modes: { system: "Systemowy", light: "Jasny", dark: "Ciemny" }, presets: { default: "Domyślny", mint: "Mięta", ocean: "Ocean", sunset: "Zachód słońca", forest: "Las", berry: "Jagoda", slate: "Łupek" } });

// Portuguese
applyTranslations('pt', {
    description: "Experiência de aprendizado interativa", facilitator: "Facilitador", attendee: "Participante", login: "Entrar", logout: "Sair", save: "Salvar", cancel: "Cancelar", delete: "Excluir", create: "Criar", import: "Importar", export: "Exportar", copy: "Copiar", loading: "Carregando...", send: "Enviar", actions: "Ações", author: "Autor", date: "Data", status: "Status", error: "Erro", success: "Sucesso", failed: "falhou", photo: "Foto", toggle_colorblind: "Modo daltônico", tts_read: "Ler este passo", tts_stop: "Parar leitura", google_login: "Entrar com Google", github_repo: "Repositório GitHub", documentation: "Documentação", change_language: "Mudar idioma", conversations: "Conversas", total: "total", refresh: "Atualizar", question: "Pergunta", answer: "Resposta", select_item: "Selecione um item para ver detalhes", no_data: "Sem dados disponíveis", toggle_theme: "Mudar tema", or: "OU", optional: "Opcional", required: "Obrigatório", ai_assistant: "Assistente IA", close: "Fechar", visibility: "Visibilidade", public: "Público", private: "Privado", skip_to_main: "Ir para o conteúdo principal", download: "Baixar", open_new_tab: "Abrir em nova aba", confirm_delete: "Tem certeza que deseja excluir este item? Esta ação não pode ser desfeita."
}, { menu_label: "Tema", mode_label: "Modo", preset_label: "Predefinição", modes: { system: "Sistema", light: "Claro", dark: "Escuro" }, presets: { default: "Padrão", mint: "Menta", ocean: "Oceano", sunset: "Pôr do sol", forest: "Floresta", berry: "Frutas vermelhas", slate: "Ardósia" } });

// Vietnamese
applyTranslations('vi', {
    description: "Trải nghiệm học tập tương tác", facilitator: "Người hướng dẫn", attendee: "Người tham gia", login: "Đăng nhập", logout: "Đăng xuất", save: "Lưu", cancel: "Hủy", delete: "Xóa", create: "Tạo", import: "Nhập", export: "Xuất", copy: "Sao chép", loading: "Đang tải...", send: "Gửi", actions: "Hành động", author: "Tác giả", date: "Ngày", status: "Trạng thái", error: "Lỗi", success: "Thành công", failed: "thất bại", photo: "Ảnh", toggle_colorblind: "Chế độ mù màu", tts_read: "Đọc bước này", tts_stop: "Dừng đọc", google_login: "Đăng nhập với Google", github_repo: "Kho GitHub", documentation: "Tài liệu", change_language: "Đổi ngôn ngữ", conversations: "Cuộc trò chuyện", total: "tổng", refresh: "Làm mới", question: "Câu hỏi", answer: "Câu trả lời", select_item: "Chọn mục để xem chi tiết", no_data: "Không có dữ liệu", toggle_theme: "Đổi giao diện", or: "HOẶC", optional: "Tùy chọn", required: "Bắt buộc", ai_assistant: "Trợ lý AI", close: "Đóng", visibility: "Hiển thị", public: "Công khai", private: "Riêng tư", skip_to_main: "Đến nội dung chính", download: "Tải xuống", open_new_tab: "Mở trong tab mới", confirm_delete: "Bạn có chắc muốn xóa mục này? Hành động này không thể hoàn tác."
}, { menu_label: "Giao diện", mode_label: "Chế độ", preset_label: "Cài đặt sẵn", modes: { system: "Hệ thống", light: "Sáng", dark: "Tối" }, presets: { default: "Mặc định", mint: "Bạc hà", ocean: "Đại dương", sunset: "Hoàng hôn", forest: "Rừng", berry: "Quả mọng", slate: "Đá phiến" } });

// Turkish
applyTranslations('tr', {
    description: "Etkileşimli öğrenme deneyimi", facilitator: "Kolaylaştırıcı", attendee: "Katılımcı", login: "Giriş yap", logout: "Çıkış yap", save: "Kaydet", cancel: "İptal", delete: "Sil", create: "Oluştur", import: "İçe aktar", export: "Dışa aktar", copy: "Kopyala", loading: "Yükleniyor...", send: "Gönder", actions: "Eylemler", author: "Yazar", date: "Tarih", status: "Durum", error: "Hata", success: "Başarılı", failed: "başarısız", photo: "Fotoğraf", toggle_colorblind: "Renk körlüğü modu", tts_read: "Bu adımı oku", tts_stop: "Okumayı durdur", google_login: "Google ile giriş yap", github_repo: "GitHub Deposu", documentation: "Belgeler", change_language: "Dili değiştir", conversations: "Konuşmalar", total: "toplam", refresh: "Yenile", question: "Soru", answer: "Cevap", select_item: "Ayrıntıları görmek için bir öğe seçin", no_data: "Veri yok", toggle_theme: "Temayı değiştir", or: "VEYA", optional: "İsteğe bağlı", required: "Gerekli", ai_assistant: "Yapay Zeka Asistanı", close: "Kapat", visibility: "Görünürlük", public: "Genel", private: "Özel", skip_to_main: "Ana içeriğe geç", download: "İndir", open_new_tab: "Yeni sekmede aç", confirm_delete: "Bu öğeyi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz."
}, { menu_label: "Tema", mode_label: "Mod", preset_label: "Ön ayar", modes: { system: "Sistem", light: "Açık", dark: "Koyu" }, presets: { default: "Varsayılan", mint: "Nane", ocean: "Okyanus", sunset: "Gün batımı", forest: "Orman", berry: "Meyve", slate: "Kayrak" } });

// Russian
applyTranslations('ru', {
    description: "Интерактивный опыт обучения", facilitator: "Ведущий", attendee: "Участник", login: "Войти", logout: "Выйти", save: "Сохранить", cancel: "Отмена", delete: "Удалить", create: "Создать", import: "Импорт", export: "Экспорт", copy: "Копировать", loading: "Загрузка...", send: "Отправить", actions: "Действия", author: "Автор", date: "Дата", status: "Статус", error: "Ошибка", success: "Успех", failed: "не удалось", photo: "Фото", toggle_colorblind: "Режим дальтонизма", tts_read: "Прочитать этот шаг", tts_stop: "Остановить чтение", google_login: "Войти через Google", github_repo: "Репозиторий GitHub", documentation: "Документация", change_language: "Сменить язык", conversations: "Беседы", total: "всего", refresh: "Обновить", question: "Вопрос", answer: "Ответ", select_item: "Выберите элемент для просмотра", no_data: "Нет данных", toggle_theme: "Сменить тему", or: "ИЛИ", optional: "Необязательно", required: "Обязательно", ai_assistant: "ИИ-ассистент", close: "Закрыть", visibility: "Видимость", public: "Публичный", private: "Приватный", skip_to_main: "Перейти к содержимому", download: "Скачать", open_new_tab: "Открыть в новой вкладке", confirm_delete: "Вы уверены, что хотите удалить этот элемент? Это действие нельзя отменить."
}, { menu_label: "Тема", mode_label: "Режим", preset_label: "Пресет", modes: { system: "Системная", light: "Светлая", dark: "Тёмная" }, presets: { default: "По умолчанию", mint: "Мята", ocean: "Океан", sunset: "Закат", forest: "Лес", berry: "Ягода", slate: "Сланец" } });

// Hebrew
applyTranslations('he', {
    description: "חוויית למידה אינטראקטיבית", facilitator: "מנחה", attendee: "משתתף", login: "התחברות", logout: "התנתקות", save: "שמור", cancel: "ביטול", delete: "מחק", create: "צור", import: "ייבוא", export: "ייצוא", copy: "העתק", loading: "טוען...", send: "שלח", actions: "פעולות", author: "מחבר", date: "תאריך", status: "סטטוס", error: "שגיאה", success: "הצלחה", failed: "נכשל", photo: "תמונה", toggle_colorblind: "מצב עיוורון צבעים", tts_read: "קרא שלב זה", tts_stop: "הפסק קריאה", google_login: "התחבר עם Google", github_repo: "מאגר GitHub", documentation: "תיעוד", change_language: "שנה שפה", conversations: "שיחות", total: "סה\"כ", refresh: "רענן", question: "שאלה", answer: "תשובה", select_item: "בחר פריט לצפייה בפרטים", no_data: "אין נתונים זמינים", toggle_theme: "שנה ערכת נושא", or: "או", optional: "אופציונלי", required: "חובה", ai_assistant: "עוזר AI", close: "סגור", visibility: "נראות", public: "ציבורי", private: "פרטי", skip_to_main: "דלג לתוכן הראשי", download: "הורד", open_new_tab: "פתח בלשונית חדשה", confirm_delete: "האם אתה בטוח שברצונך למחוק פריט זה? פעולה זו אינה ניתנת לביטול."
}, { menu_label: "ערכת נושא", mode_label: "מצב", preset_label: "הגדרה מוגדרת", modes: { system: "מערכת", light: "בהיר", dark: "כהה" }, presets: { default: "ברירת מחדל", mint: "מנטה", ocean: "אוקיינוס", sunset: "שקיעה", forest: "יער", berry: "פירות יער", slate: "צפחה" } });

// Arabic
applyTranslations('ar', {
    description: "تجربة تعلم تفاعلية", facilitator: "ميسّر", attendee: "مشارك", login: "تسجيل الدخول", logout: "تسجيل الخروج", save: "حفظ", cancel: "إلغاء", delete: "حذف", create: "إنشاء", import: "استيراد", export: "تصدير", copy: "نسخ", loading: "جار التحميل...", send: "إرسال", actions: "إجراءات", author: "المؤلف", date: "التاريخ", status: "الحالة", error: "خطأ", success: "نجاح", failed: "فشل", photo: "صورة", toggle_colorblind: "وضع عمى الألوان", tts_read: "اقرأ هذه الخطوة", tts_stop: "توقف عن القراءة", google_login: "تسجيل الدخول بواسطة Google", github_repo: "مستودع GitHub", documentation: "التوثيق", change_language: "تغيير اللغة", conversations: "المحادثات", total: "المجموع", refresh: "تحديث", question: "سؤال", answer: "إجابة", select_item: "اختر عنصراً لعرض التفاصيل", no_data: "لا توجد بيانات", toggle_theme: "تغيير السمة", or: "أو", optional: "اختياري", required: "مطلوب", ai_assistant: "مساعد الذكاء الاصطناعي", close: "إغلاق", visibility: "الرؤية", public: "عام", private: "خاص", skip_to_main: "انتقل إلى المحتوى الرئيسي", download: "تنزيل", open_new_tab: "فتح في علامة تبويب جديدة", confirm_delete: "هل أنت متأكد أنك تريد حذف هذا العنصر؟ لا يمكن التراجع عن هذا الإجراء."
}, { menu_label: "السمة", mode_label: "الوضع", preset_label: "إعداد مسبق", modes: { system: "النظام", light: "فاتح", dark: "داكن" }, presets: { default: "افتراضي", mint: "نعناع", ocean: "محيط", sunset: "غروب", forest: "غابة", berry: "توت", slate: "أردواز" } });

// Persian
applyTranslations('fa', {
    description: "تجربه یادگیری تعاملی", facilitator: "تسهیلگر", attendee: "شرکت‌کننده", login: "ورود", logout: "خروج", save: "ذخیره", cancel: "لغو", delete: "حذف", create: "ایجاد", import: "وارد کردن", export: "صادر کردن", copy: "کپی", loading: "در حال بارگذاری...", send: "ارسال", actions: "عملیات", author: "نویسنده", date: "تاریخ", status: "وضعیت", error: "خطا", success: "موفقیت", failed: "ناموفق", photo: "عکس", toggle_colorblind: "حالت کوررنگی", tts_read: "خواندن این مرحله", tts_stop: "توقف خواندن", google_login: "ورود با Google", github_repo: "مخزن GitHub", documentation: "مستندات", change_language: "تغییر زبان", conversations: "مکالمات", total: "مجموع", refresh: "بازنشانی", question: "سؤال", answer: "پاسخ", select_item: "یک مورد را برای مشاهده جزئیات انتخاب کنید", no_data: "داده‌ای موجود نیست", toggle_theme: "تغییر پوسته", or: "یا", optional: "اختیاری", required: "الزامی", ai_assistant: "دستیار هوش مصنوعی", close: "بستن", visibility: "نمایش", public: "عمومی", private: "خصوصی", skip_to_main: "رفتن به محتوای اصلی", download: "دانلود", open_new_tab: "باز کردن در تب جدید", confirm_delete: "آیا مطمئن هستید که می‌خواهید این مورد را حذف کنید؟ این عمل قابل بازگشت نیست."
}, { menu_label: "پوسته", mode_label: "حالت", preset_label: "پیش‌تنظیم", modes: { system: "سیستم", light: "روشن", dark: "تاریک" }, presets: { default: "پیش‌فرض", mint: "نعنا", ocean: "اقیانوس", sunset: "غروب", forest: "جنگل", berry: "توت", slate: "سنگ لوح" } });

// Hindi
applyTranslations('hi', {
    description: "इंटरैक्टिव सीखने का अनुभव", facilitator: "फैसिलिटेटर", attendee: "प्रतिभागी", login: "लॉगिन", logout: "लॉगआउट", save: "सहेजें", cancel: "रद्द करें", delete: "हटाएं", create: "बनाएं", import: "आयात करें", export: "निर्यात करें", copy: "कॉपी करें", loading: "लोड हो रहा है...", send: "भेजें", actions: "कार्रवाई", author: "लेखक", date: "तिथि", status: "स्थिति", error: "त्रुटि", success: "सफलता", failed: "विफल", photo: "फोटो", toggle_colorblind: "कलर ब्लाइंड मोड", tts_read: "यह चरण पढ़ें", tts_stop: "पढ़ना बंद करें", google_login: "Google से लॉगिन करें", github_repo: "GitHub रिपॉजिटरी", documentation: "दस्तावेज़", change_language: "भाषा बदलें", conversations: "बातचीत", total: "कुल", refresh: "रिफ्रेश करें", question: "प्रश्न", answer: "उत्तर", select_item: "विवरण देखने के लिए आइटम चुनें", no_data: "कोई डेटा उपलब्ध नहीं", toggle_theme: "थीम बदलें", or: "या", optional: "वैकल्पिक", required: "आवश्यक", ai_assistant: "AI सहायक", close: "बंद करें", visibility: "दृश्यता", public: "सार्वजनिक", private: "निजी", skip_to_main: "मुख्य सामग्री पर जाएं", download: "डाउनलोड करें", open_new_tab: "नए टैब में खोलें", confirm_delete: "क्या आप वाकई इस आइटम को हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।"
}, { menu_label: "थीम", mode_label: "मोड", preset_label: "प्रीसेट", modes: { system: "सिस्टम", light: "लाइट", dark: "डार्क" }, presets: { default: "डिफ़ॉल्ट", mint: "मिंट", ocean: "ओशन", sunset: "सनसेट", forest: "फ़ॉरेस्ट", berry: "बेरी", slate: "स्लेट" } });

// Bengali
applyTranslations('bn', {
    description: "ইন্টারেক্টিভ শেখার অভিজ্ঞতা", facilitator: "ফ্যাসিলিটেটর", attendee: "অংশগ্রহণকারী", login: "লগইন", logout: "লগআউট", save: "সংরক্ষণ", cancel: "বাতিল", delete: "মুছুন", create: "তৈরি করুন", import: "আমদানি", export: "রপ্তানি", copy: "কপি", loading: "লোড হচ্ছে...", send: "পাঠান", actions: "কার্যক্রম", author: "লেখক", date: "তারিখ", status: "অবস্থা", error: "ত্রুটি", success: "সফল", failed: "ব্যর্থ", photo: "ছবি", toggle_colorblind: "বর্ণান্ধ মোড", tts_read: "এই ধাপটি পড়ুন", tts_stop: "পড়া বন্ধ করুন", google_login: "Google দিয়ে লগইন", github_repo: "GitHub রিপোজিটরি", documentation: "ডকুমেন্টেশন", change_language: "ভাষা পরিবর্তন", conversations: "কথোপকথন", total: "মোট", refresh: "রিফ্রেশ", question: "প্রশ্ন", answer: "উত্তর", select_item: "বিস্তারিত দেখতে আইটেম নির্বাচন করুন", no_data: "কোনো ডেটা নেই", toggle_theme: "থিম পরিবর্তন", or: "অথবা", optional: "ঐচ্ছিক", required: "আবশ্যিক", ai_assistant: "AI সহকারী", close: "বন্ধ", visibility: "দৃশ্যমানতা", public: "সর্বজনীন", private: "ব্যক্তিগত", skip_to_main: "মূল বিষয়বস্তুতে যান", download: "ডাউনলোড", open_new_tab: "নতুন ট্যাবে খুলুন", confirm_delete: "আপনি কি নিশ্চিত এই আইটেমটি মুছতে চান? এই ক্রিয়াটি পূর্বাবস্থায় ফেরানো যাবে না।"
}, { menu_label: "থিম", mode_label: "মোড", preset_label: "প্রিসেট", modes: { system: "সিস্টেম", light: "লাইট", dark: "ডার্ক" }, presets: { default: "ডিফল্ট", mint: "মিন্ট", ocean: "মহাসাগর", sunset: "সূর্যাস্ত", forest: "বন", berry: "বেরি", slate: "স্লেট" } });

// Thai
applyTranslations('th', {
    description: "ประสบการณ์การเรียนรู้เชิงโต้ตอบ", facilitator: "ผู้อำนวยความสะดวก", attendee: "ผู้เข้าร่วม", login: "เข้าสู่ระบบ", logout: "ออกจากระบบ", save: "บันทึก", cancel: "ยกเลิก", delete: "ลบ", create: "สร้าง", import: "นำเข้า", export: "ส่งออก", copy: "คัดลอก", loading: "กำลังโหลด...", send: "ส่ง", actions: "การดำเนินการ", author: "ผู้เขียน", date: "วันที่", status: "สถานะ", error: "ข้อผิดพลาด", success: "สำเร็จ", failed: "ล้มเหลว", photo: "รูปภาพ", toggle_colorblind: "โหมดตาบอดสี", tts_read: "อ่านขั้นตอนนี้", tts_stop: "หยุดอ่าน", google_login: "เข้าสู่ระบบด้วย Google", github_repo: "คลัง GitHub", documentation: "เอกสาร", change_language: "เปลี่ยนภาษา", conversations: "การสนทนา", total: "ทั้งหมด", refresh: "รีเฟรช", question: "คำถาม", answer: "คำตอบ", select_item: "เลือกรายการเพื่อดูรายละเอียด", no_data: "ไม่มีข้อมูล", toggle_theme: "เปลี่ยนธีม", or: "หรือ", optional: "ไม่บังคับ", required: "จำเป็น", ai_assistant: "ผู้ช่วย AI", close: "ปิด", visibility: "การมองเห็น", public: "สาธารณะ", private: "ส่วนตัว", skip_to_main: "ข้ามไปยังเนื้อหาหลัก", download: "ดาวน์โหลด", open_new_tab: "เปิดในแท็บใหม่", confirm_delete: "คุณแน่ใจหรือไม่ว่าต้องการลบรายการนี้? การดำเนินการนี้ไม่สามารถย้อนกลับได้"
}, { menu_label: "ธีม", mode_label: "โหมด", preset_label: "ค่าที่ตั้งไว้", modes: { system: "ระบบ", light: "สว่าง", dark: "มืด" }, presets: { default: "ค่าเริ่มต้น", mint: "มิ้นต์", ocean: "มหาสมุทร", sunset: "พระอาทิตย์ตก", forest: "ป่า", berry: "เบอร์รี่", slate: "หินชนวน" } });

// Traditional Chinese
applyTranslations('zh-TW', {
    description: "互動學習體驗", facilitator: "引導者", attendee: "參與者", login: "登入", logout: "登出", save: "儲存", cancel: "取消", delete: "刪除", create: "建立", import: "匯入", export: "匯出", copy: "複製", loading: "載入中...", send: "傳送", actions: "操作", author: "作者", date: "日期", status: "狀態", error: "錯誤", success: "成功", failed: "失敗", photo: "照片", toggle_colorblind: "色盲模式", tts_read: "朗讀此步驟", tts_stop: "停止朗讀", google_login: "使用 Google 登入", github_repo: "GitHub 儲存庫", documentation: "文件", change_language: "變更語言", conversations: "對話", total: "總計", refresh: "重新整理", question: "問題", answer: "回答", select_item: "選擇項目以檢視詳細資訊", no_data: "無可用資料", toggle_theme: "切換主題", or: "或", optional: "選填", required: "必填", ai_assistant: "AI 助手", close: "關閉", visibility: "可見性", public: "公開", private: "私人", skip_to_main: "跳至主要內容", download: "下載", open_new_tab: "在新分頁開啟", confirm_delete: "確定要刪除此項目嗎？此操作無法復原。"
}, { menu_label: "主題", mode_label: "模式", preset_label: "預設", modes: { system: "系統", light: "淺色", dark: "深色" }, presets: { default: "預設", mint: "薄荷", ocean: "海洋", sunset: "日落", forest: "森林", berry: "莓果", slate: "石板" } });

console.log('\nAll common+theme sections translated!');
